package com.landray.kmss.km.review.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2021-04-14T11:05:29.244+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://webservice.review.km.kmss.landray.com/", name = "IKmReviewWebserviceService")
@XmlSeeAlso({ObjectFactory.class})
public interface IKmReviewWebserviceService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "approveProcess", targetNamespace = "http://webservice.review.km.kmss.landray.com/", className = "com.landray.kmss.km.review.webservice.ApproveProcess")
    @WebMethod
    @ResponseWrapper(localName = "approveProcessResponse", targetNamespace = "http://webservice.review.km.kmss.landray.com/", className = "com.landray.kmss.km.review.webservice.ApproveProcessResponse")
    public java.lang.String approveProcess(
        @WebParam(name = "arg0", targetNamespace = "")
        com.landray.kmss.km.review.webservice.KmReviewParamterForm arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateReviewInfo", targetNamespace = "http://webservice.review.km.kmss.landray.com/", className = "com.landray.kmss.km.review.webservice.UpdateReviewInfo")
    @WebMethod
    @ResponseWrapper(localName = "updateReviewInfoResponse", targetNamespace = "http://webservice.review.km.kmss.landray.com/", className = "com.landray.kmss.km.review.webservice.UpdateReviewInfoResponse")
    public java.lang.String updateReviewInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        com.landray.kmss.km.review.webservice.KmReviewParamterForm arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addReview", targetNamespace = "http://webservice.review.km.kmss.landray.com/", className = "com.landray.kmss.km.review.webservice.AddReview")
    @WebMethod
    @ResponseWrapper(localName = "addReviewResponse", targetNamespace = "http://webservice.review.km.kmss.landray.com/", className = "com.landray.kmss.km.review.webservice.AddReviewResponse")
    public java.lang.String addReview(
        @WebParam(name = "arg0", targetNamespace = "")
        com.landray.kmss.km.review.webservice.KmReviewParamterForm arg0
    ) throws Exception_Exception;
}
