
package com.sap.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZCS_RDDS", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZCSRDDS {


    /**
     * 
     * @param eData
     * @param eMessage
     * @param eMsgty
     * @param iDate
     */
    @WebMethod(operationName = "Zppf011", action = "urn:sap-com:document:sap:soap:functions:mc-style:ZCS_RDDS:Zppf011Request")
    @RequestWrapper(localName = "Zppf011", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.service.Zppf011")
    @ResponseWrapper(localName = "Zppf011Response", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.service.Zppf011Response")
    public void zppf011(
        @WebParam(name = "EtVerinfo", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<TableOfZstrRddsVeridInfo> etVerinfo,
        @WebParam(name = "IDate", targetNamespace = "")
        String iDate,
        @WebParam(name = "IMatnr", targetNamespace = "")
        String iMatnr,
        @WebParam(name = "EMessage", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eMessage,
        @WebParam(name = "EMsgty", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eMsgty);

    /**
     * 
     * @param eData
     * @param eMessage
     * @param eMsgty
     * @param iDate
     */
    @WebMethod(operationName = "Zppf012", action = "urn:sap-com:document:sap:soap:functions:mc-style:ZCS_RDDS:Zppf012Request")
    @RequestWrapper(localName = "Zppf012", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.service.Zppf012")
    @ResponseWrapper(localName = "Zppf012Response", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.service.Zppf012Response")
    public void zppf012(
        @WebParam(name = "IDate", targetNamespace = "")
        String iDate,
        @WebParam(name = "IMatnr", targetNamespace = "")
        String iMatnr,
        @WebParam(name = "EData", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eData,
        @WebParam(name = "EMessage", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eMessage,
        @WebParam(name = "EMsgty", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eMsgty);

    /**
     * 
     * @param eData
     * @param eMessage
     * @param eMsgty
     * @param iDate
     */
    @WebMethod(operationName = "Zppf013", action = "urn:sap-com:document:sap:soap:functions:mc-style:ZCS_RDDS:Zppf013Request")
    @RequestWrapper(localName = "Zppf013", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.service.Zppf013")
    @ResponseWrapper(localName = "Zppf013Response", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.service.Zppf013Response")
    public void zppf013(
        @WebParam(name = "EtGylxInfo", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<TableOfZstrRddsGylxInfo> etGylxInfo,
        @WebParam(name = "IDate", targetNamespace = "")
        String iDate,
        @WebParam(name = "IMatnr", targetNamespace = "")
        String iMatnr,
        @WebParam(name = "EMessage", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eMessage,
        @WebParam(name = "EMsgty", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eMsgty);

    /**
     * 
     * @param eData
     * @param eMessage
     * @param iMatnr
     * @param eMsgty
     * @param iDate
     */
    @WebMethod(operationName = "Zppf014", action = "urn:sap-com:document:sap:soap:functions:mc-style:ZCS_RDDS:Zppf014Request")
    @RequestWrapper(localName = "Zppf014", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.service.Zppf014")
    @ResponseWrapper(localName = "Zppf014Response", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.service.Zppf014Response")
    public void zppf014(
        @WebParam(name = "EBomlist", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<TableOfZstrRddsBomlist> eBomlist,
        @WebParam(name = "IDate", targetNamespace = "")
        String iDate,
        @WebParam(name = "IMatnr", targetNamespace = "")
        String iMatnr);

    /**
     * 
     * @param eData
     * @param eMessage
     * @param iBomno
     * @param eMsgty
     */
    @WebMethod(operationName = "Zppf015", action = "urn:sap-com:document:sap:soap:functions:mc-style:ZCS_RDDS:Zppf015Request")
    @RequestWrapper(localName = "Zppf015", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.service.Zppf015")
    @ResponseWrapper(localName = "Zppf015Response", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.service.Zppf015Response")
    public void zppf015(
        @WebParam(name = "IBomno", targetNamespace = "")
        String iBomno,
        @WebParam(name = "EData", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eData,
        @WebParam(name = "EMessage", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eMessage,
        @WebParam(name = "EMsgty", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eMsgty);

    /**
     * 
     * @param eBomlist
     * @param eMessage
     * @param iMatnr
     * @param eMsgty
     * @param iDate
     */
    @WebMethod(operationName = "Zppf016", action = "urn:sap-com:document:sap:soap:functions:mc-style:ZCS_RDDS:Zppf016Request")
    @RequestWrapper(localName = "Zppf016", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.webservice.Zppf016")
    @ResponseWrapper(localName = "Zppf016Response", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.webservice.Zppf016Response")
    public void zppf016(
        @WebParam(name = "EBomlist", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<TableOfZstrRddsBomlist2> eBomlist,
        @WebParam(name = "IDate", targetNamespace = "")
        String iDate,
        @WebParam(name = "IMatnr", targetNamespace = "")
        String iMatnr,
        @WebParam(name = "EMessage", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eMessage,
        @WebParam(name = "EMsgty", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eMsgty);
}
