
package com.sap.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZCS_ZPPF014", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "doc/zcs_zppf014.wsdl")
public class ZCSZPPF014
    extends Service
{

    private final static URL ZCSZPPF014_WSDL_LOCATION;
    private final static WebServiceException ZCSZPPF014_EXCEPTION;
    private final static QName ZCSZPPF014_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZCS_ZPPF014");

    static {
        WebServiceException e = null;

        URL url = ZCSRDDS.class.getClassLoader().getResource("doc/zcs_zppf014.wsdl");
        ZCSZPPF014_WSDL_LOCATION = url;
        ZCSZPPF014_EXCEPTION = e;
    }

    public ZCSZPPF014() {
        super(__getWsdlLocation(), ZCSZPPF014_QNAME);
    }

    public ZCSZPPF014(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZCSZPPF014_QNAME, features);
    }

    public ZCSZPPF014(URL wsdlLocation) {
        super(wsdlLocation, ZCSZPPF014_QNAME);
    }

    public ZCSZPPF014(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZCSZPPF014_QNAME, features);
    }

    public ZCSZPPF014(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZCSZPPF014(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZCSRDDS
     */
    @WebEndpoint(name = "ZCS_ZPPF014")
    public ZCSRDDS getZCSZPPF014() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZCS_ZPPF014"), ZCSRDDS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZCSRDDS
     */
    @WebEndpoint(name = "ZCS_ZPPF014")
    public ZCSRDDS getZCSZPPF014(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZCS_ZPPF014"), ZCSRDDS.class, features);
    }

    /**
     * 
     * @return
     *     returns ZCSRDDS
     */
    @WebEndpoint(name = "ZCS_ZPPF014_soap12")
    public ZCSRDDS getZCSZPPF014Soap12() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZCS_ZPPF014_soap12"), ZCSRDDS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZCSRDDS
     */
    @WebEndpoint(name = "ZCS_ZPPF014_soap12")
    public ZCSRDDS getZCSZPPF014Soap12(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZCS_ZPPF014_soap12"), ZCSRDDS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZCSZPPF014_EXCEPTION!= null) {
            throw ZCSZPPF014_EXCEPTION;
        }
        return ZCSZPPF014_WSDL_LOCATION;
    }

}
